'use strict';
(() => {
const $=id=>document.getElementById(id),KEY='bloom-boom-v1';
const stations=[{id:'garden',x:-5,z:1.45,r:1.75,name:'Flower garden',emoji:'🌻'},{id:'workshop',x:0,z:1.25,r:1.65,name:'Bouquet table',emoji:'🎀'},{id:'market',x:5,z:1.55,r:1.65,name:'Town market',emoji:'🏪'},{id:'upgrades',x:0,z:5.6,r:1.6,name:'Upgrade board',emoji:'✨'},{id:'orchard',x:-5,z:6.6,r:1.55,name:'Berry orchard',emoji:'🫐'},{id:'kitchen',x:5,z:6.6,r:1.55,name:'Jam kitchen',emoji:'🫙'}];
const solids=[[-6.85,-3.15,-2.82,.85],[-1.55,1.55,-2.05,.2],[3.4,6.6,-2.05,.92],[-1.1,1.1,3.25,4.8],[-6.8,-3.2,3.6,5.85],[3.45,6.55,3.8,5.85]];
const canStand=(x,z)=>!solids.some(([a,b,c,d])=>x+.24>a&&x-.24<b&&z+.24>c&&z-.24<d);
const initial=()=>({money:0,raw:0,goods:0,berries:0,jam:0,capacity:12,gather:0,process:0,quality:0,helper:0,expansion:0,oven:0,orchardUnlocked:false,totalGathered:0,totalCrafted:0,totalBerries:0,totalJamCrafted:0,totalJamSold:0,totalSold:0,ordersDone:0,reputation:0,chapter:0,player:{x:-3,z:2.2},sound:true,updated:Date.now()});
let state;try{state={...initial(),...JSON.parse(localStorage.getItem(KEY)||'null')};if(!Number.isFinite(state.player?.x))state.player={x:-3,z:2.2}}catch{state=initial()}
const migrated=!canStand(state.player.x,state.player.z);if(migrated)state.player.z=state.player.z>2?6.7:1.6;
const player={x:state.player.x,z:state.player.z,vx:0,vz:0,heading:0,moving:false},input={x:0,z:0},keys=new Set();let zone=null,last=performance.now(),workClock=0,helperClock=0,deferredInstall=null,panelOpen=false,audio;
const format=v=>'$'+Math.floor(v).toLocaleString();const cap=()=>state.capacity+state.expansion*4;const held=()=>state.raw+state.goods*2+state.berries+state.jam*2;const saleBouquet=()=>12+state.quality*5;const saleJam=()=>29+state.quality*4;
function save(){state.player={x:player.x,z:player.z};state.updated=Date.now();try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}}
if(migrated)save();
function ping(freq){if(!state.sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.025,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.11);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.12)}catch{}}
function popup(text){const p=document.createElement('div');p.className='float';p.textContent=text;p.style.left=(35+Math.random()*30)+'%';p.style.top=(42+Math.random()*16)+'%';$('popups').append(p);setTimeout(()=>p.remove(),900)}
function message(text){$('zoneMessage').textContent=text}function near(){return stations.find(s=>Math.hypot(player.x-s.x,player.z-s.z)<s.r)||null}
const story=[
 {title:'A fresh start',speaker:'MIRA · YOUR NEIGHBOR',line:'The old flower shop has been closed for years. Pick a few blooms and let’s bring it back to life.',goal:'Collect 4 flowers',icon:'🌻',target:4,progress:()=>state.totalGathered,reward:15},
 {title:'First bouquet',speaker:'MIRA',line:'A little ribbon can turn ordinary flowers into something someone will treasure.',goal:'Make 2 bouquets',icon:'🎀',target:2,progress:()=>state.totalCrafted,reward:22},
 {title:'Open for business',speaker:'MIRA',line:'The stall is ready. Take your bouquets into town and meet our first customers.',goal:'Sell 2 bouquets',icon:'🏪',target:2,progress:()=>state.totalSold,reward:28},
 {title:'A familiar face',speaker:'ELI · TOWN COURIER',line:'The town noticed your stall. Fill a special order, and I’ll spread the word.',goal:'Complete 1 town order',icon:'📦',target:1,progress:()=>state.ordersDone,reward:40},
 {title:'The orchard gate',speaker:'MIRA',line:'There’s an abandoned berry orchard behind the shop. We could make much more than bouquets.',goal:'Unlock the berry orchard',icon:'🗝️',target:1,progress:()=>state.orchardUnlocked?1:0,reward:35},
 {title:'Something sweeter',speaker:'MIRA',line:'The first berries are ready! Gather enough to try the old family recipe.',goal:'Collect 6 berries',icon:'🫐',target:6,progress:()=>state.totalBerries,reward:30},
 {title:'Grandma’s recipe',speaker:'ELI',line:'The kitchen still works. Three berries make one jar of jam. I know who will buy it.',goal:'Make 2 jars of jam',icon:'🫙',target:2,progress:()=>state.totalJamCrafted,reward:45},
 {title:'A sweeter market',speaker:'MIRA',line:'Bouquets and jam together? Now we have a real neighborhood business.',goal:'Sell 2 jars of jam',icon:'🏪',target:2,progress:()=>state.totalJamSold,reward:60},
 {title:'The spring festival',speaker:'ELI',line:'The spring festival is coming. Become the florist everyone in town can count on.',goal:'Complete 4 town orders',icon:'🎉',target:4,progress:()=>state.ordersDone,reward:100}
];
function advance(){let changed=false;while(state.chapter<story.length&&story[state.chapter].progress()>=story[state.chapter].target){const c=story[state.chapter];state.money+=c.reward;state.chapter++;changed=true;popup('CHAPTER COMPLETE +'+format(c.reward));ping(930)}if(changed){save();if(panelOpen&&$('panelBody').dataset.type==='story')openPanel('story')}}
function mission(){const c=story[state.chapter];if(c)return[c.icon,c.goal,Math.min(100,c.progress()/c.target*100),`Chapter ${state.chapter+1} · ${c.title}`];const o=currentOrder();return['⭐',`Grow your shop · fill ${o.name}'s order`,Math.min(100,(state.reputation%5)*20),'Your town story continues']}
function gather(){const n=Math.min(1+state.expansion,cap()-held());if(n<=0){message('Backpack full! Visit a workshop 🎀');return}state.raw+=n;state.totalGathered+=n;window.bloomScene?.animate('flower',{x:-5,z:-1},{x:player.x,z:player.z},n);popup('+'+n+' 🌻');ping(520);advance();save()}
function gatherBerries(){if(!state.orchardUnlocked)return unlockOrchard();const n=Math.min(1+Math.floor(state.expansion/2),cap()-held());if(n<=0){message('Backpack full! Visit the kitchen 🫙');return}state.berries+=n;state.totalBerries+=n;window.bloomScene?.animate('berry',{x:-5,z:5},{x:player.x,z:player.z},n);popup('+'+n+' 🫐');ping(560);advance();save()}
function craft(){if(state.raw<2){message('Collect at least 2 flowers first 🌻');return}state.raw-=2;state.goods++;state.totalCrafted++;window.bloomScene?.animate('craft',{x:player.x,z:player.z},{x:0,z:-.9},1);popup('+1 💐');ping(670);advance();save()}
function cook(){if(!state.orchardUnlocked){message('Unlock the orchard first 🗝️');return}if(state.berries<3){message('Collect 3 berries to make jam 🫐');return}state.berries-=3;state.jam++;state.totalJamCrafted++;window.bloomScene?.animate('cook',{x:player.x,z:player.z},{x:5,z:5},1);popup('+1 🫙');ping(700);advance();save()}
function orders(){const normal=[{name:'Eli',need:{goods:2},reward:42,emoji:'💐',text:'2 bouquets for a birthday'},{name:'Nora',need:{goods:3},reward:68,emoji:'🎁',text:'3 bouquets for the café'},{name:'Mira',need:{goods:2,jam:1},reward:104,emoji:'🌸',text:'Flowers and jam for a picnic'},{name:'Theo',need:{jam:2},reward:98,emoji:'🍓',text:'2 jars for the bakery'}];return state.orchardUnlocked?normal:[normal[0],normal[1]]}
function currentOrder(){return orders()[state.ordersDone%orders().length]}
function canDeliver(o){return Object.entries(o.need).every(([k,v])=>state[k]>=v)}
function deliver(){const o=currentOrder();if(!canDeliver(o))return false;for(const [k,v] of Object.entries(o.need))state[k]-=v;state.totalSold+=o.need.goods||0;state.totalJamSold+=o.need.jam||0;state.money+=o.reward;state.reputation++;state.ordersDone++;window.bloomScene?.animate('order',{x:player.x,z:player.z},{x:5,z:-.2},1);popup('ORDER +'+format(o.reward)+' ⭐');ping(900);advance();save();if(panelOpen&&$('panelBody').dataset.type==='orders')openPanel('orders');return true}
function sell(){if(canDeliver(currentOrder()))return deliver();if(state.goods>0){state.goods--;state.money+=saleBouquet();state.totalSold++;window.bloomScene?.animate('sale',{x:player.x,z:player.z},{x:5,z:-.2},1);popup('+'+format(saleBouquet()));ping(860)}else if(state.jam>0){state.jam--;state.money+=saleJam();state.totalJamSold++;window.bloomScene?.animate('saleJam',{x:player.x,z:player.z},{x:5,z:-.2},1);popup('+'+format(saleJam()));ping(890)}else{message('Bring a bouquet or a jar to sell');return}advance();save()}
function unlockOrchard(){if(state.orchardUnlocked)return;const cost=120;if(state.money<cost){message(`Orchard costs ${format(cost)} · need ${format(cost-state.money)} more`);return}state.money-=cost;state.orchardUnlocked=true;window.bloomScene?.animate('unlock',{x:-5,z:5},{x:player.x,z:player.z},1);popup('ORCHARD UNLOCKED! 🫐');advance();save()}
function action(){if(!zone){message('Walk into a glowing work circle');return}({garden:gather,workshop:craft,market:sell,upgrades:()=>openPanel('upgrades'),orchard:gatherBerries,kitchen:cook})[zone.id]();refresh()}
function refresh(){const [icon,task,pct,title]=mission();$('money').textContent=format(state.money);$('raw').textContent=state.raw;$('goods').textContent=state.goods;$('berries').textContent=state.berries;$('jam').textContent=state.jam;$('berryCounter').hidden=!state.orchardUnlocked;$('jamCounter').hidden=!state.orchardUnlocked;$('bag').textContent=held()+' / '+cap();$('missionIcon').textContent=icon;$('missionText').textContent=task;$('chapterName').textContent=title;$('missionBar').style.width=pct+'%';$('upgradeHint').textContent='from '+format(upgrades()[0].cost);$('action').textContent=zone?({garden:'PICK',workshop:'MAKE',market:'SELL',upgrades:'SHOP',orchard:state.orchardUnlocked?'PICK':'UNLOCK',kitchen:'COOK'})[zone.id]:'GO!'}
function upgrades(){return [{id:'capacity',icon:'🎒',name:'Bigger backpack',detail:'+6 carrying space',cost:25+(state.capacity-12)/6*28},{id:'gather',icon:'✂️',name:'Sharp clippers',detail:'Pick flowers and berries faster',cost:35*Math.pow(2,state.gather)},{id:'process',icon:'🎀',name:'Ribbon press',detail:'Make bouquets faster',cost:55*Math.pow(2,state.process)},{id:'quality',icon:'🌷',name:'Premium flowers',detail:'Earn more per item',cost:80*Math.pow(2,state.quality)},{id:'helper',icon:'👩‍🌾',name:'Garden helper',detail:'Gathers while you roam',cost:120*Math.pow(2,state.helper)},{id:'expansion',icon:'🌼',name:'Expand flower beds',detail:'+1 flower per pick and +4 space',cost:150*Math.pow(2,state.expansion)},{id:'oven',icon:'🔥',name:'Better stove',detail:'Cook jam faster',cost:120*Math.pow(2,state.oven),locked:!state.orchardUnlocked}].map(u=>({...u,cost:Math.floor(u.cost)}))}
function buy(id){const u=upgrades().find(x=>x.id===id);if(!u||u.locked||state.money<u.cost)return;state.money-=u.cost;if(id==='capacity')state.capacity+=6;else state[id]++;popup('UPGRADED! ✨');save();openPanel('upgrades');refresh()}
function openPanel(type){panelOpen=true;$('panel').hidden=false;$('panelBody').dataset.type=type;if(type==='upgrades')$('panelBody').innerHTML=`<h2>✨ Build your business</h2><p>Invest in faster work and more room to carry products.</p>${upgrades().map(u=>`<div class="upgrade-row"><span class="emoji">${u.icon}</span><span class="detail"><strong>${u.name}</strong><small>${u.detail}</small></span><button data-buy="${u.id}" ${state.money<u.cost||u.locked?'disabled':''}>${u.locked?'LOCKED':format(u.cost)}</button></div>`).join('')}<button class="reset" id="resetFarm">Start a new game</button>`;
else if(type==='orders'){const o=currentOrder();$('panelBody').innerHTML=`<h2>📦 Town orders</h2><p>Deliver a special request at the market for extra money and reputation.</p><div class="order-card"><strong>${o.emoji} ${o.name}: ${o.text}</strong><small>${Object.entries(o.need).map(([k,v])=>`${k==='goods'?'💐':'🫙'} ${state[k]}/${v}`).join(' · ')}</small><div class="reward">Reward ${format(o.reward)} + ⭐ reputation</div><button id="deliverOrder" ${!canDeliver(o)||zone?.id!=='market'?'disabled':''}>${zone?.id!=='market'?'Visit market':canDeliver(o)?'Deliver order':'Gather products'}</button></div><p>Orders completed: ${state.ordersDone} · Reputation: ⭐ ${state.reputation}</p>`}
else if(type==='story'){const c=story[state.chapter];$('panelBody').innerHTML=`<h2>📖 The greenhouse story</h2><p>Reopen the flower shop and prepare for the town’s spring festival.</p><div class="story-panel"><span class="speaker">${c?.speaker||'MIRA · THE FESTIVAL'}</span><blockquote>“${c?.line||'Look what we built together! The shop belongs to the town now. Keep making their days brighter.'}”</blockquote><div class="goal">${c?.icon||'🌟'} ${c?.goal||'Keep growing'} · ${c?Math.min(c.target,c.progress())+'/'+c.target:'Story complete'}</div></div><p>Chapter ${Math.min(state.chapter+1,story.length)} of ${story.length} · ⭐ ${state.reputation} reputation</p>`}
else if(type==='install')$('panelBody').innerHTML='<h2>📲 Install Bloom & Boom</h2><p>Play full screen from your home screen.</p><div class="install-help">On Android Chrome: tap <b>⋮ → Add to Home screen → Install</b>. If the page is tiny, turn off <b>Desktop site</b> first.</div>';
else $('panelBody').innerHTML='<h2>🎮 How to play</h2><ol><li>Move the joystick or use WASD / arrow keys.</li><li>Collect flowers at 🌻, turn two into a bouquet at 🎀, and sell at 🏪.</li><li>Fill town orders at the market for bonuses and reputation.</li><li>Follow the story to unlock 🫐 berries, cook jam at 🫙, and expand the world.</li><li>Buy upgrades to speed up work and hire a helper.</li></ol><div class="install-help">Drag on the world to turn the camera. The action button works at each station.</div>'}
function closePanel(){panelOpen=false;$('panel').hidden=true}
$('upgradeButton').onclick=()=>openPanel('upgrades');$('helpButton').onclick=()=>openPanel('help');$('storyButton').onclick=()=>openPanel('story');$('ordersButton').onclick=()=>openPanel('orders');$('closePanel').onclick=closePanel;$('panel').addEventListener('click',e=>{if(e.target===$('panel'))closePanel();const b=e.target.closest('[data-buy]');if(b)buy(b.dataset.buy);if(e.target.id==='deliverOrder'){deliver();refresh()}if(e.target.id==='resetFarm'&&confirm('Erase your saved business and start over?')){state=initial();player.x=state.player.x;player.z=state.player.z;player.vx=player.vz=0;save();closePanel();refresh()}});$('action').onclick=action;
$('install').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null}else openPanel('install')};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});$('sound').onclick=()=>{state.sound=!state.sound;$('sound').textContent=state.sound?'♫':'♪̸';save()};
const stick=$('stick'),knob=$('stickKnob');let pointer=null;function moveStick(e){const r=stick.getBoundingClientRect(),x=(e.clientX-(r.left+r.width/2))/(r.width*.34),z=(e.clientY-(r.top+r.height/2))/(r.height*.34),l=Math.max(1,Math.hypot(x,z));input.x=x/l;input.z=z/l;knob.style.transform=`translate(${input.x*32}px,${input.z*32}px)`}stick.addEventListener('pointerdown',e=>{e.preventDefault();pointer=e.pointerId;stick.setPointerCapture(pointer);moveStick(e)});stick.addEventListener('pointermove',e=>{if(e.pointerId===pointer)moveStick(e)});const stop=e=>{if(e.pointerId!==pointer)return;pointer=null;input.x=input.z=0;knob.style.transform='translate(0,0)'};stick.addEventListener('pointerup',stop);stick.addEventListener('pointercancel',stop);
window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','w','a','s','d','e','W','A','S','D','E'].includes(e.key)){e.preventDefault();keys.add(e.key.toLowerCase());if(e.key===' '||e.key.toLowerCase()==='e')action()}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
$('fallback').addEventListener('click',e=>{const b=e.target.closest('[data-destination]');if(!b)return;const s=stations.find(v=>v.id===b.dataset.destination);if(!s)return;player.x=s.x;player.z=s.z;zone=s;action();refresh()});
function frame(t){const dt=Math.min(.05,(t-last)/1000);last=t;if(!panelOpen){const kx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),kz=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);let ix=Math.abs(input.x)+Math.abs(input.z)>.04?input.x:kx,iz=Math.abs(input.x)+Math.abs(input.z)>.04?input.z:kz,l=Math.hypot(ix,iz);if(l>.08){ix/=Math.max(1,l);iz/=Math.max(1,l)}else{ix=0;iz=0}const drag=l>.08?8:13;player.vx+=(ix*4.2-player.vx)*Math.min(1,dt*drag);player.vz+=(iz*4.2-player.vz)*Math.min(1,dt*drag);player.moving=Math.hypot(player.vx,player.vz)>.15;if(player.moving){const nx=Math.max(-9,Math.min(9,player.x+player.vx*dt)),nz=Math.max(-7,Math.min(7,player.z+player.vz*dt));if(canStand(nx,player.z))player.x=nx;else player.vx=0;if(canStand(player.x,nz))player.z=nz;else player.vz=0;player.heading=Math.atan2(player.vx,player.vz);state.player.x=player.x;state.player.z=player.z}const newZone=near();if(newZone!==zone){zone=newZone;workClock=0;if(zone)message(zone.emoji+' '+zone.name+' — stay here to work');else message(mission()[1]);refresh()}if(zone&&zone.id!=='upgrades'){workClock+=dt;const period=zone.id==='garden'||zone.id==='orchard'?Math.max(.29,.85-state.gather*.16):zone.id==='workshop'?Math.max(.38,1.15-state.process*.2):zone.id==='kitchen'?Math.max(.4,1.3-state.oven*.2):.5;if(workClock>=period){workClock=0;if(zone.id==='garden'&&held()<cap())gather();if(zone.id==='workshop'&&state.raw>=2)craft();if(zone.id==='market'&&(state.goods+state.jam)>0)sell();if(zone.id==='orchard'&&state.orchardUnlocked&&held()<cap())gatherBerries();if(zone.id==='kitchen'&&state.berries>=3)cook();refresh()}}helperClock+=dt;if(state.helper&&helperClock>Math.max(1.2,3-state.helper*.35)){helperClock=0;if(held()<cap()){state.raw++;state.totalGathered++;advance();save();refresh()}}if(player.moving&&t%1200<40)save()}window.bloomScene?.draw(t,player,state,stations);requestAnimationFrame(frame)}
if(!window.bloomScene){$('fallback').hidden=false;$('world').style.display='none'}refresh();if(!state.introSeen){state.introSeen=true;save();setTimeout(()=>openPanel('story'),300)}window.bloomGameReady=true;requestAnimationFrame(frame);
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
})();
