'use strict';
const KEY='sunny-acres-save-v1';
const CROPS=[{id:'sunflower',name:'Sunflower',emoji:'🌻',seed:'🌱',time:8000,value:6,unlock:1},{id:'carrot',name:'Carrot',emoji:'🥕',seed:'🌿',time:13000,value:11,unlock:2},{id:'strawberry',name:'Berry',emoji:'🍓',seed:'🌱',time:19000,value:19,unlock:4}];
const $=id=>document.getElementById(id);
const fresh=()=>({cash:0,xp:0,level:1,plots:1,selected:'sunflower',inventory:{sunflower:0,carrot:0,strawberry:0},fields:Array(6).fill(null),tool:0,irrigation:0,workers:0,market:0,totalHarvest:0,ordersDone:0,updated:Date.now()});
let state;
try{state=Object.assign(fresh(),JSON.parse(localStorage.getItem(KEY)||'null')||{});if(!Array.isArray(state.fields)||state.fields.length!==6)state.fields=fresh().fields;state.inventory=Object.assign(fresh().inventory,state.inventory)}catch{state=fresh()}
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
const fmt=n=>'$'+Math.floor(n).toLocaleString();
const crop=id=>CROPS.find(c=>c.id===id);
const duration=c=>c.time*Math.pow(.83,state.irrigation);
const amount=()=>1+state.tool;
const value=c=>c.value*(1+state.market*.25);
function save(){state.updated=Date.now();try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}}
function toast(s){const el=$('toast');el.textContent=s;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2400)}
function levelXP(n){return n*100}
function gainXP(n){state.xp+=n;while(state.xp>=levelXP(state.level)){state.xp-=levelXP(state.level);state.level++;state.cash+=state.level*5;toast(`Level ${state.level}! Bonus ${fmt(state.level*5)} 🎉`)}}
function harvest(i,automatic=false){const f=state.fields[i];if(!f||Date.now()<f.ready)return false;const c=crop(f.crop);state.inventory[c.id]+=amount();state.totalHarvest+=amount();state.fields[i]=null;gainXP(10);if(!automatic)toast(`Harvested ${amount()} ${c.name.toLowerCase()}!`);save();render();return true}
function plant(i,id=state.selected){if(i>=state.plots)return;const c=crop(id);if(!c||state.level<c.unlock)return;if(state.fields[i])return harvest(i);state.fields[i]={crop:id,ready:Date.now()+duration(c)};save();render()}
function buy(type){let price;if(type==='plot')price=Math.floor(25*Math.pow(1.85,state.plots-1));if(type==='tool')price=Math.floor(35*Math.pow(1.85,state.tool));if(type==='irrigation')price=Math.floor(55*Math.pow(1.9,state.irrigation));if(type==='worker')price=Math.floor(90*Math.pow(2.1,state.workers));if(type==='market')price=Math.floor(80*Math.pow(2,state.market));if(state.cash<price){toast(`You need ${fmt(price-state.cash)} more`);return}if(type==='plot'&&state.plots>=6)return;if(type==='worker'&&state.workers>=3)return;state.cash-=price;if(type==='plot')state.plots++;else state[type]++;gainXP(15);save();render();toast(type==='plot'?'New land unlocked! 🌱':'Upgrade purchased! ✨')}
function sell(){const total=CROPS.reduce((n,c)=>n+state.inventory[c.id]*value(c),0);if(!total)return;state.cash+=Math.floor(total);CROPS.forEach(c=>state.inventory[c.id]=0);gainXP(Math.max(5,Math.floor(total/3)));save();render();toast(`Sold your harvest for ${fmt(total)}!`)}
const orderNeeds=[{id:'sunflower',count:3,bonus:14},{id:'carrot',count:2,bonus:22},{id:'strawberry',count:2,bonus:38}];
function order(){return orderNeeds[state.ordersDone%3]}
function fillOrder(){const o=order();if(state.inventory[o.id]<o.count)return;state.inventory[o.id]-=o.count;state.cash+=o.bonus;state.ordersDone++;gainXP(25);save();render();toast(`Order delivered! +${fmt(o.bonus)} 🎁`)}
function render(){ $('cash').textContent=fmt(state.cash);$('levelLabel').textContent=`LEVEL ${state.level}`;$('xpLabel').textContent=`${state.xp} / ${levelXP(state.level)} XP`;$('xpBar').style.width=(state.xp/levelXP(state.level)*100)+'%';$('plotCount').textContent=`${state.plots} / 6 plots`;$('workerStatus').textContent=state.workers?`👩‍🌾 ${state.workers} helper${state.workers>1?'s':''} at work`:'👩‍🌾 You are farming solo';
if(window.farm3d)window.farm3d.refresh(state,CROPS);
const fallback=$('fallbackPlots');if(fallback)fallback.innerHTML=state.fields.map((f,i)=>{const locked=i>=state.plots;const ready=f&&Date.now()>=f.ready;const c=f?crop(f.crop):null;return `<button class="fallback-plot ${locked?'locked':''} ${ready?'ripe':''}" data-plot="${i}" aria-label="${locked?'Locked plot':ready?'Harvest '+c.name:f?'Growing '+c.name:'Plant crop'}"><span>${locked?'🔒':f?(ready?c.emoji:c.seed):'＋'}</span><small>${locked?'Unlock':f?(ready?'Harvest':Math.ceil((f.ready-Date.now())/1000)+'s'):'Plant'}</small></button>`}).join('');
$('cropButtons').innerHTML=CROPS.map(c=>`<button class="crop-button ${state.selected===c.id?'selected':''}" data-crop="${c.id}" ${state.level<c.unlock?'disabled':''}>${c.emoji} ${state.level<c.unlock?'Lv '+c.unlock:c.name}</button>`).join('');
$('inventory').innerHTML=CROPS.map(c=>`<div class="inv-item">${c.emoji}<small>${state.inventory[c.id]} ${c.name}</small></div>`).join('');const total=CROPS.reduce((n,c)=>n+state.inventory[c.id]*value(c),0);$('sellValue').textContent=fmt(total);$('sellBtn').disabled=!total;
const upgrades=[{id:'plot',emoji:'🗺️',name:'Expand farmland',desc:'Unlock another field',level:state.plots,max:6,price:Math.floor(25*Math.pow(1.85,state.plots-1))},{id:'tool',emoji:'🧤',name:'Better tools',desc:`Harvest ${amount()+1} crops per plot`,level:state.tool,price:Math.floor(35*Math.pow(1.85,state.tool))},{id:'irrigation',emoji:'💧',name:'Irrigation',desc:'Crops grow 17% faster',level:state.irrigation,price:Math.floor(55*Math.pow(1.9,state.irrigation))},{id:'worker',emoji:'👩‍🌾',name:'Hire a helper',desc:'Auto harvest & replant while here',level:state.workers,max:3,price:Math.floor(90*Math.pow(2.1,state.workers))},{id:'market',emoji:'🏪',name:'Market stall',desc:'Sell crops for 25% more',level:state.market,price:Math.floor(80*Math.pow(2,state.market))}];$('upgrades').innerHTML=upgrades.map(u=>`<button class="upgrade" data-buy="${u.id}" ${u.level===u.max?'disabled':''}><span class="emoji">${u.emoji}</span><span class="details"><strong>${u.name}${u.level?' · '+u.level:''}</strong><small>${u.desc}</small></span><span class="price">${u.level===u.max?'MAX':fmt(u.price)}</span></button>`).join('');const o=order(),c=crop(o.id);$('orders').innerHTML=`<div class="order"><div><b>${c.emoji} ${o.count} ${c.name}s</b><small>${state.inventory[o.id]} / ${o.count} ready · Reward ${fmt(o.bonus)}</small></div><button id="orderBtn" ${state.inventory[o.id]<o.count?'disabled':''}>Deliver</button></div><small style="color:#9aa692">Completed: ${state.ordersDone}</small>`}
const onPlot=i=>{if(i>=state.plots){toast('Expand farmland to unlock this plot');return}plant(i)};window.farm3d?.setPlotHandler(onPlot);$('fallbackPlots').addEventListener('click',e=>{const target=e.target.closest('[data-plot]');if(target)onPlot(Number(target.dataset.plot))});
$('cropButtons').addEventListener('click',e=>{const el=e.target.closest('[data-crop]');if(!el)return;state.selected=el.dataset.crop;save();render()});$('upgrades').addEventListener('click',e=>{const el=e.target.closest('[data-buy]');if(el)buy(el.dataset.buy)});$('orders').addEventListener('click',e=>{if(e.target.id==='orderBtn')fillOrder()});$('sellBtn').addEventListener('click',sell);$('resetBtn').addEventListener('click',()=>{if(confirm('Start a new farm? This erases your current progress.')){state=fresh();save();render()}});
let lastTick=0;function tick(){const now=Date.now();if(now-lastTick<450)return;lastTick=now;if(state.workers){let work=0;for(let i=0;i<state.plots&&work<state.workers;i++){const f=state.fields[i];if(f&&now>=f.ready){harvest(i,true);state.fields[i]={crop:f.crop,ready:now+duration(crop(f.crop))};work++}}if(work)save()}render()}
// Offline growth uses persisted ready timestamps; automatic work runs only while the game is open.
render();setInterval(tick,500);

let deferredInstall=null;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('installBtn').hidden=false});
$('installBtn').addEventListener('click',async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('installBtn').hidden=true}else $('installGuide').hidden=false});
$('closeGuide').addEventListener('click',()=>{$('installGuide').hidden=true});
window.addEventListener('appinstalled',()=>{$('installBtn').hidden=true;toast('Sunny Acres installed!')});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
