'use strict';
(() => {
const $=id=>document.getElementById(id),KEY='bloom-boom-v1';
const stations=[{id:'garden',x:-5,z:-1,r:2.1,name:'Garden',emoji:'🌻'},{id:'workshop',x:0,z:-1,r:2.1,name:'Bouquet table',emoji:'🎀'},{id:'market',x:5,z:-1,r:2.1,name:'Flower market',emoji:'🏪'},{id:'upgrades',x:0,z:4,r:1.8,name:'Upgrade board',emoji:'✨'}];
const initial=()=>({money:0,raw:0,goods:0,capacity:12,gather:0,process:0,quality:0,helper:0,expansion:0,totalSold:0,player:{x:-3,z:1},sound:true,updated:Date.now()});
let state;try{state={...initial(),...JSON.parse(localStorage.getItem(KEY)||'null')};if(!Number.isFinite(state.player?.x))state.player={x:-3,z:1}}catch{state=initial()}
const player={x:state.player.x,z:state.player.z,heading:0,moving:false},input={x:0,z:0},keys=new Set();let zone=null,last=performance.now(),workClock=0,helperClock=0,deferredInstall=null,panelOpen=false,popupTimer=0;
const format=v=>'$'+Math.floor(v).toLocaleString();const save=()=>{state.player={x:player.x,z:player.z};state.updated=Date.now();try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}};
const capacity=()=>state.capacity+state.expansion*4;const rawYield=()=>1+state.expansion;const sale=()=>12+state.quality*5;
let audio;function ping(freq){if(!state.sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.025,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.11);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.12)}catch{}}
function popup(text){const p=document.createElement('div');p.className='float';p.textContent=text;p.style.left=(35+Math.random()*30)+'%';p.style.top=(42+Math.random()*16)+'%';$('popups').append(p);setTimeout(()=>p.remove(),900)}
function message(text){$('zoneMessage').textContent=text}
function nearest(){return stations.find(s=>Math.hypot(player.x-s.x,player.z-s.z)<s.r)||null}
function next(){if(state.raw>=2&&state.goods<Math.max(2,capacity()/3))return ['workshop','Turn flowers into bouquets 🎀',state.raw/capacity()*100];if(state.goods>0)return ['market','Sell bouquets at the market 🏪',state.goods/(capacity()/2)*100];return ['garden','Collect flowers in the garden 🌻',state.raw/capacity()*100]}
function gather(){const n=Math.min(rawYield(),capacity()-state.raw-state.goods*2);if(n<=0){message('Backpack full! Visit the workshop 🎀');return}state.raw+=n;popup('+'+n+' 🌻');ping(520);save()}
function craft(){if(state.raw<2){message('Collect at least 2 flowers first 🌻');return}state.raw-=2;state.goods++;popup('+1 💐');ping(670);save()}
function sell(){if(!state.goods){message('Bring bouquets from the workshop 🎀');return}state.goods--;state.money+=sale();state.totalSold++;popup('+'+format(sale()));ping(860);save()}
function action(){if(!zone){message('Walk into a glowing circle to work');return}if(zone.id==='garden')gather();if(zone.id==='workshop')craft();if(zone.id==='market')sell();if(zone.id==='upgrades')openPanel('upgrades');refresh()}
function refresh(){const [dest,task,pct]=next();$('money').textContent=format(state.money);$('raw').textContent=state.raw;$('goods').textContent=state.goods;$('bag').textContent=(state.raw+state.goods*2)+' / '+capacity();$('missionIcon').textContent=stations.find(s=>s.id===dest).emoji;$('missionText').textContent=task;$('missionBar').style.width=Math.min(100,pct)+'%';$('upgradeHint').textContent='from '+format(upgrades()[0].cost);if(zone){$('action').textContent=zone.id==='garden'?'PICK':zone.id==='workshop'?'MAKE':zone.id==='market'?'SELL':'SHOP'}else $('action').textContent='GO!'}
function upgrades(){return [{id:'capacity',icon:'🎒',name:'Bigger backpack',detail:'+6 carrying space',cost:25+Math.max(0,(state.capacity-12)/6)*28},{id:'gather',icon:'✂️',name:'Sharp clippers',detail:'Pick flowers faster',cost:35*Math.pow(2,state.gather)},{id:'process',icon:'🎀',name:'Ribbon press',detail:'Make bouquets faster',cost:55*Math.pow(2,state.process)},{id:'quality',icon:'🌷',name:'Premium flowers',detail:'Earn $5 more per bouquet',cost:80*Math.pow(2,state.quality)},{id:'helper',icon:'👩‍🌾',name:'Garden helper',detail:'Gathers while you roam',cost:120*Math.pow(2,state.helper)},{id:'expansion',icon:'🌼',name:'Expand flower beds',detail:'+1 flower per pick and +4 space',cost:150*Math.pow(2,state.expansion)}].map(u=>({...u,cost:Math.floor(u.cost)}))}
function buy(id){const u=upgrades().find(x=>x.id===id);if(!u||state.money<u.cost)return;state.money-=u.cost;if(id==='capacity')state.capacity+=6;else state[id]++;popup('UPGRADED! ✨');save();openPanel('upgrades');refresh()}
function openPanel(type){panelOpen=true;$('panel').hidden=false;if(type==='upgrades'){$('panelBody').innerHTML=`<h2>✨ Build your business</h2><p>Upgrade, then return to the world to keep growing.</p>${upgrades().map(u=>`<div class="upgrade-row"><span class="emoji">${u.icon}</span><span class="detail"><strong>${u.name}</strong><small>${u.detail}</small></span><button data-buy="${u.id}" ${state.money<u.cost?'disabled':''}>${format(u.cost)}</button></div>`).join('')}<button class="reset" id="resetFarm">Start a new game</button>`}else if(type==='install'){$('panelBody').innerHTML='<h2>📲 Install Bloom & Boom</h2><p>Play full screen from your home screen.</p><div class="install-help">On Android Chrome: tap <b>⋮ → Add to Home screen → Install</b>. If the page is tiny, turn off <b>Desktop site</b> in the Chrome menu first. Reopen the page after changing that setting.</div>'}else{$('panelBody').innerHTML='<h2>🎮 How to play</h2><ol><li>Move the joystick or use WASD / arrow keys to walk around.</li><li>Stand near the glowing 🌻 garden to collect flowers automatically. Tap PICK to speed up.</li><li>Take flowers to the 🎀 table. Two flowers make one bouquet.</li><li>Bring bouquets to the 🏪 market for cash.</li><li>Buy upgrades to carry more, work faster, and hire help.</li></ol><div class="install-help">Drag on the world to turn the camera. The ACTION button works at every station.</div>'}}
function closePanel(){panelOpen=false;$('panel').hidden=true}
$('upgradeButton').onclick=()=>openPanel('upgrades');$('helpButton').onclick=()=>openPanel('help');$('closePanel').onclick=closePanel;$('panel').addEventListener('click',e=>{if(e.target===$('panel'))closePanel();const b=e.target.closest('[data-buy]');if(b)buy(b.dataset.buy);if(e.target.id==='resetFarm'&&confirm('Erase your saved business and start over?')){state=initial();player.x=state.player.x;player.z=state.player.z;save();closePanel();refresh()}});$('action').onclick=action;
$('install').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null}else openPanel('install')};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});$('sound').onclick=()=>{state.sound=!state.sound;$('sound').textContent=state.sound?'♫':'♪̸';save()};
const stick=$('stick'),knob=$('stickKnob');let pointer=null;function moveStick(e){const r=stick.getBoundingClientRect(),x=(e.clientX-(r.left+r.width/2))/(r.width*.34),z=(e.clientY-(r.top+r.height/2))/(r.height*.34),l=Math.max(1,Math.hypot(x,z));input.x=x/l;input.z=z/l;knob.style.transform=`translate(${input.x*32}px,${input.z*32}px)`}stick.addEventListener('pointerdown',e=>{e.preventDefault();pointer=e.pointerId;stick.setPointerCapture(pointer);moveStick(e)});stick.addEventListener('pointermove',e=>{if(e.pointerId===pointer)moveStick(e)});const stop=e=>{if(e.pointerId!==pointer)return;pointer=null;input.x=input.z=0;knob.style.transform='translate(0,0)'};stick.addEventListener('pointerup',stop);stick.addEventListener('pointercancel',stop);
window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','w','a','s','d','e','W','A','S','D','E'].includes(e.key)){e.preventDefault();keys.add(e.key.toLowerCase());if(e.key===' '||e.key.toLowerCase()==='e')action()}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
$('fallback').addEventListener('click',e=>{const b=e.target.closest('[data-destination]');if(!b)return;const s=stations.find(v=>v.id===b.dataset.destination);player.x=s.x;player.z=s.z;zone=s;action();refresh()});
function frame(t){const dt=Math.min(.05,(t-last)/1000);last=t;if(!panelOpen){const kx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),kz=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);let ix=Math.abs(input.x)+Math.abs(input.z)>.04?input.x:kx,iz=Math.abs(input.x)+Math.abs(input.z)>.04?input.z:kz,l=Math.hypot(ix,iz);player.moving=l>.08;if(player.moving){ix/=Math.max(1,l);iz/=Math.max(1,l);const speed=4.1;player.x=Math.max(-9,Math.min(9,player.x+ix*dt*speed));player.z=Math.max(-7,Math.min(7,player.z+iz*dt*speed));player.heading=Math.atan2(ix,iz);state.player.x=player.x;state.player.z=player.z}const newZone=nearest();if(newZone!==zone){zone=newZone;workClock=0;if(zone)message(zone.emoji+' '+zone.name+' — stay here to work');else message(next()[1]);refresh()}if(zone&&zone.id!=='upgrades'){workClock+=dt;const period=zone.id==='garden'?Math.max(.28,.85-state.gather*.16):zone.id==='workshop'?Math.max(.38,1.15-state.process*.2):.5;if(workClock>=period){workClock=0;if(zone.id==='garden'&&state.raw+state.goods*2<capacity())gather();if(zone.id==='workshop'&&state.raw>=2)craft();if(zone.id==='market'&&state.goods>0)sell();refresh()}}helperClock+=dt;if(state.helper&&helperClock>Math.max(1.2,3-state.helper*.35)){helperClock=0;if(state.raw+state.goods*2<capacity()){state.raw++;save();refresh()}}if(player.moving&&t%1200<40)save()}window.bloomScene?.draw(t,player,state,stations);requestAnimationFrame(frame)}
if(!window.bloomScene){$('fallback').hidden=false;$('world').style.display='none'}refresh();window.bloomGameReady=true;requestAnimationFrame(frame);
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
})();
