import * as THREE from 'three';

// Bloom & Boom: Garden Hotel. Original characters, world and gameplay.
const $=id=>document.getElementById(id), KEY='bloom-boom-hotel-v1';
const roomPrice=n=>80+Math.round(n*72+n*n*9), roomPos=i=>({x:i%2?-4.45:4.45,z:5+Math.floor(i/2)*6.2});
const facilities={bath:{name:'Guest bathroom',icon:'🚿',cost:70,x:4.5,z:-4},lounge:{name:'Flower lounge',icon:'💐',cost:150,x:-4.5,z:-3.2},parking:{name:'Garden parking',icon:'🚗',cost:320,x:9,z:-10},cafe:{name:'Garden café',icon:'☕',cost:480,x:8,z:11},pool:{name:'Sunflower pool',icon:'🏊',cost:950,x:-9,z:15}};
const defaults=()=>({money:25,flowers:0,bouquets:0,jam:0,rooms:[{built:true,level:1,status:'vacant',flowers:false}],facilities:{bath:false,lounge:false,parking:false,cafe:false,pool:false},staff:{reception:0,cleaner:0,gardener:0,florist:0,attendant:0},guests:[],guestSeq:0,checked:0,cleaned:0,served:0,lost:0,harvested:0,crafted:0,decorated:0,story:0,shift:0,shiftServed:0,shiftLost:0,stars:1,bathStock:3,poolStock:3,rep:0,event:'',eventTime:0,player:{x:0,z:-2},sceneTime:0,saved:Date.now()});
let state;try{state={...defaults(),...JSON.parse(localStorage.getItem(KEY)||'null')};if(!Array.isArray(state.rooms)||!state.rooms.length)throw Error('rooms')}catch{state=defaults();try{const old=JSON.parse(localStorage.getItem('bloom-boom-v1')||'null');if(old){state.money=Math.max(25,old.money||0);state.flowers=old.raw||0;state.bouquets=old.goods||0;state.jam=old.jam||0}}catch{}}
state.facilities={...defaults().facilities,...state.facilities};state.staff={...defaults().staff,...state.staff};state.guests=Array.isArray(state.guests)?state.guests:[];state.rooms=state.rooms.map(r=>({built:true,level:1,flowers:false,...r,status:r.status==='occupied'?'dirty':(r.status||'vacant')}));state.guests=[];
const save=()=>{state.player={x:player.x,z:player.z};state.saved=Date.now();try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}};
const fmt=n=>'$'+Math.floor(n).toLocaleString(),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const player={x:state.player?.x||0,z:state.player?.z||-2,vx:0,vz:0,heading:0},keys=new Set(),input={x:0,z:0},actors=new Map(),staffActors=new Map(),effects=[];
let zone=null,workTime=0,spawnTime=4,staffTime=0,uiTime=0,last=performance.now(),panel=false,waypoint=null,deferredInstall=null,renderer=null,scene=null,camera=null,world=null,avatar=null,ground=null,canvas2d=null,changedWorld=true,graphicMode='';
const quests=[
 {title:'Mira opens the doors',text:'Check in your first garden guest',test:s=>s.checked>=1,reward:60},
 {title:'A fresh start',text:'Clean a room after checkout',test:s=>s.cleaned>=1,reward:50},
 {title:'Flowers for every guest',text:'Pick 3 flowers in the greenhouse',test:s=>s.harvested>=3,reward:45},
 {title:'A welcome bouquet',text:'Make 1 bouquet at the worktable',test:s=>s.crafted>=1,reward:65},
 {title:'More space to grow',text:'Open the second guest room',test:s=>s.rooms.length>=2,reward:90},
 {title:'The first five reviews',text:'Check in 5 guests',test:s=>s.checked>=5,reward:100},
 {title:'Hospitality blooms',text:'Open the flower lounge',test:s=>s.facilities.lounge,reward:120},
 {title:'A team takes shape',text:'Hire any 2 helpers',test:s=>Object.values(s.staff).reduce((a,b)=>a+b,0)>=2,reward:130},
 {title:'The garden menu',text:'Open the garden café',test:s=>s.facilities.cafe,reward:200},
 {title:'Festival weekend',text:'Serve 20 guests and open 5 rooms',test:s=>s.served>=20&&s.rooms.length>=5,reward:300},
 {title:'The secret greenhouse',text:'Open the pool and decorate 8 rooms',test:s=>s.facilities.pool&&s.decorated>=8,reward:500},
];
function toast(text){const el=$('toast');el.textContent=text;el.classList.remove('show');void el.offsetWidth;el.classList.add('show')}
function earn(n,label){state.money+=n;effects.push({x:player.x,y:1,z:player.z,label:'+'+fmt(n),age:0});toast('+'+fmt(n)+' '+label);save()}
function spend(n){if(state.money<n){toast('Need '+fmt(n)+' more cash');return false}state.money-=n;save();return true}
function progress(){let did=false;while(state.story<quests.length&&quests[state.story].test(state)){const q=quests[state.story++];state.stars=1+Math.floor(state.story/2);state.money+=q.reward;toast('★ '+q.title+'  +'+fmt(q.reward));did=true}if(did){save();updateUI()}}
function builtRooms(){return state.rooms.length}
function queue(){return state.guests.filter(g=>g.phase==='queue').sort((a,b)=>a.id-b.id)}
function roomVacant(){return state.rooms.findIndex(r=>r.status==='vacant')}
function spawnGuest(){if(queue().length>=7)return;const id=++state.guestSeq,vip=Math.random()<.17,guest={id,phase:'walkin',x:(Math.random()-.5)*1.5,z:-13,tx:(queue().length%3-1)*.75,tz:-6.4-queue().length*.65,patience:vip?40:60,max:vip?40:60,vip,look:id%5,happiness:1,stay:14+Math.random()*13,room:-1};state.guests.push(guest);changedWorld=true;save()}
function checkIn(){const g=queue()[0],i=roomVacant();if(!g){toast('No guest in line');return false}if(i<0){toast('Build or clean a room first');return false}const r=state.rooms[i],p=roomPos(i);r.status='occupied';r.guest=g.id;g.phase='toRoom';g.room=i;g.path=[{x:2.1,z:-6.4},{x:2.1,z:-3.5},{x:p.x>0?2.1:-2.1,z:p.z+.3},{x:p.x,z:p.z+.3}];g.tx=g.path[0].x;g.tz=g.path[0].z;if(state.facilities.bath){if(state.bathStock>0)state.bathStock--;else g.happiness-=.18}if(state.facilities.pool){if(state.poolStock>0)state.poolStock--;else g.happiness-=.18}state.checked++;state.shiftServed++;changedWorld=true;toast('🔑 Room '+(i+1)+' · '+(g.vip?'VIP guest':'guest'));progress();save();return true}
function cleanRoom(i){const r=state.rooms[i];if(!r||r.status!=='dirty')return false;r.status='vacant';r.guest=null;state.cleaned++;changedWorld=true;effects.push({x:roomPos(i).x,y:1,z:roomPos(i).z,label:'✨',age:0});toast('✨ Room '+(i+1)+' cleaned');progress();save();return true}
function pick(){state.flowers++;state.harvested++;effects.push({x:-10,y:1,z:-8,label:'🌻',age:0});if(state.harvested%4===0)toast('🌻 '+state.flowers+' flowers');progress();save()}
function craft(){if(state.flowers<2){toast('Pick 2 flowers first');return false}state.flowers-=2;state.bouquets++;state.crafted++;toast('💐 Bouquet ready');progress();save();return true}
function decorate(i){const r=state.rooms[i];if(state.bouquets<1){toast('Make a bouquet first');return false}if(r.flowers){toast('This room already has flowers');return false}state.bouquets--;r.flowers=true;state.decorated++;changedWorld=true;toast('💐 Guest room upgraded');progress();save();return true}
function buyRoom(){const n=state.rooms.length;if(n>=20){toast('All rooms are open');return false}const cost=roomPrice(n);if(!spend(cost))return false;state.rooms.push({built:true,level:1,status:'vacant',flowers:false});toast('🏨 Room '+(n+1)+' is open');changedWorld=true;progress();save();updateUI();return true}
function buyFacility(id){const f=facilities[id];if(state.facilities[id])return; if(!spend(f.cost))return;state.facilities[id]=true;toast(f.icon+' '+f.name+' is open');changedWorld=true;progress();save();updateUI();openPanel('build')}
function improveRoom(i){const r=state.rooms[i];const cost=95*r.level;if(!spend(cost))return;r.level++;toast('🛏️ Room '+(i+1)+' level '+r.level);changedWorld=true;save();openPanel('build')}
function hire(id){const prices={reception:130,cleaner:160,gardener:135,florist:180,attendant:240},cost=prices[id]*(1+state.staff[id]);if(!spend(cost))return;state.staff[id]++;toast('👥 New '+id+' hired');changedWorld=true;progress();save();openPanel('staff')}
function interact(){if(!zone){toast('Step onto a glowing circle');return}const {id,i}=zone;if(id==='reception')checkIn();else if(id==='garden')pick();else if(id==='workshop')craft();else if(id==='room') {if(!cleanRoom(i))decorate(i)}else if(id==='newroom')buyRoom();else if(id==='bath'){if(!state.facilities.bath)buyFacility('bath');else{state.bathStock=5;toast('🧻 Bathroom restocked');changedWorld=true;save()}}else if(id==='lounge'){if(!state.facilities.lounge)buyFacility('lounge');else if(state.bouquets){state.bouquets--;earn(23,'flower display')}else toast('Make bouquets at the workshop')}else if(id==='parking'){if(!state.facilities.parking)buyFacility('parking');else toast('🚗 Parking ready for arrivals')}else if(id==='cafe'||id==='pool'){if(!state.facilities[id])buyFacility(id);else if(id==='cafe'){if(state.jam){state.jam--;earn(38,'garden breakfast')}else toast('Make jam in the flower kitchen')}else{state.poolStock=5;toast('🏊 Clean towels restocked');changedWorld=true;save()}}else if(id==='jam'){if(state.flowers>=3){state.flowers-=3;state.jam++;toast('🫙 Garden jam ready');save()}else toast('Pick 3 flowers first')};updateUI()}
function zones(){const a=[{id:'reception',x:0,z:-4.2,r:1.6,label:'🛎️ Check in guest',action:'CHECK IN'},{id:'garden',x:-10,z:-8,r:2,label:'🌻 Pick flowers',action:'PICK'},{id:'workshop',x:-5,z:-8,r:1.7,label:'🎀 Make bouquets',action:'MAKE'},{id:'jam',x:-5,z:-12,r:1.5,label:'🫙 Cook jam',action:'COOK'}];for(const [id,f] of Object.entries(facilities))a.push({id,x:f.x,z:f.z,r:1.7,label:f.icon+' '+(state.facilities[id]?f.name:'Open '+f.name+' · '+fmt(f.cost)),action:state.facilities[id]?'WORK':'BUILD'});for(let i=0;i<state.rooms.length;i++){const p=roomPos(i),r=state.rooms[i];a.push({id:'room',i,x:p.x,z:p.z+.7,r:1.7,label:'🛏️ Room '+(i+1)+' · '+(r.status==='dirty'?'clean':r.flowers?'decorated':'add flowers'),action:r.status==='dirty'?'CLEAN':'FLOWERS'})}if(state.rooms.length<20){const p=roomPos(state.rooms.length);a.push({id:'newroom',x:p.x>0?2.15:-2.15,z:p.z,r:1.4,label:'🏗️ Open room '+(state.rooms.length+1)+' · '+fmt(roomPrice(state.rooms.length)),action:'BUILD'})}return a}
function nearest(){return zones().find(q=>Math.hypot(player.x-q.x,player.z-q.z)<q.r)||null}
function guestTick(dt){spawnTime-=dt;if(spawnTime<=0){spawnGuest();spawnTime=clamp(14-builtRooms()*.4-(state.event==='Festival crowd'?4:0),6,14)}for(const g of [...state.guests]){if(g.phase==='queue'){g.patience-=dt*(state.event==='Rainy day'?1.25:1);if(g.patience<=0){state.guests=state.guests.filter(v=>v!==g);state.lost++;state.shiftLost++;state.rep=Math.max(0,state.rep-1);toast('💢 A guest left the line');save();continue}}else if(g.phase==='staying'){g.stay-=dt;if(g.stay<=0){const p=roomPos(g.room);g.phase='leave';g.path=[{x:p.x>0?2.1:-2.1,z:p.z+.3},{x:2.1,z:-3.5},{x:2.1,z:-6.4},{x:0,z:-10}];g.tx=g.path[0].x;g.tz=g.path[0].z}}else{const dx=g.tx-g.x,dz=g.tz-g.z,d=Math.hypot(dx,dz),speed=g.phase==='leave'?2.4:2.15;if(d>speed*dt){g.x+=dx/d*speed*dt;g.z+=dz/d*speed*dt}else{g.x=g.tx;g.z=g.tz;if(g.phase==='walkin')g.phase='queue';else if(g.path?.length>1){g.path.shift();g.tx=g.path[0].x;g.tz=g.path[0].z}else if(g.phase==='toRoom')g.phase='staying';else if(g.phase==='leave'){const r=state.rooms[g.room];if(r){r.status='dirty';r.guest=null;changedWorld=true}const amount=Math.round((28+r.level*12+(r.flowers?18:0)+(g.vip?30:0)+(state.facilities.lounge?6:0)+(state.facilities.parking?5:0)+(state.facilities.cafe?9:0)+(state.facilities.pool?12:0))*(g.happiness??1));state.served++;state.rep++;state.money+=amount;state.guests=state.guests.filter(v=>v!==g);effects.push({x:0,y:1,z:-4,label:'+'+fmt(amount),age:0});toast('💵 Checkout +'+fmt(amount));progress();save()}}}}
if(state.shiftServed>=5+state.shift*2){const prize=100+state.shift*55;state.money+=prize;state.shift++;state.shiftServed=0;state.shiftLost=0;toast('⭐ Shift complete +'+fmt(prize));save()}else if(state.shiftLost>=2){state.shiftServed=0;state.shiftLost=0;toast('Shift restarted · serve guests faster');save()}}
function staffTick(dt){staffTime+=dt;if(staffTime<1.2)return;staffTime=0;const s=state.staff;state.staffTimers=state.staffTimers||{};for(const id of Object.keys(s))state.staffTimers[id]=(state.staffTimers[id]||0)+1.2;if(s.reception&&state.staffTimers.reception>clamp(5-s.reception*.8,2,5)){state.staffTimers.reception=0;if(queue().length&&roomVacant()>=0)checkIn()}if(s.cleaner&&state.staffTimers.cleaner>clamp(7-s.cleaner,2,7)){state.staffTimers.cleaner=0;const i=state.rooms.findIndex(r=>r.status==='dirty');if(i>=0)cleanRoom(i)}if(s.gardener&&state.staffTimers.gardener>clamp(5-s.gardener,2,5)){state.staffTimers.gardener=0;pick()}if(s.florist&&state.staffTimers.florist>clamp(6-s.florist,2,6)){state.staffTimers.florist=0;if(state.flowers>=2)craft()}if(s.attendant&&state.staffTimers.attendant>7){state.staffTimers.attendant=0;state.bathStock=5;state.poolStock=5;changedWorld=true}}
function eventTick(dt){state.sceneTime+=dt;if(state.eventTime>0){state.eventTime-=dt;if(state.eventTime<=0){state.event='';toast('The resort is calm again')}}else if(Math.floor(state.sceneTime)%94===0&&state.sceneTime>3){state.event=['Festival crowd','Rainy day','VIP visit'][Math.floor(state.sceneTime/94)%3];state.eventTime=50;toast('⚡ '+state.event+'!')} }
function updateUI(){const q=quests[state.story],target=5+state.shift*2;$('bank').innerHTML='💵 <b>'+fmt(state.money)+'</b>';$('star').textContent='★ '+state.stars;$('chapter').textContent=q?.title||'The garden hotel is yours';$('objective').textContent=q?.text||'Grow rooms, welcome guests and complete shifts';$('progress').style.width=q?Math.min(95,state.story/quests.length*100)+'%':Math.min(100,state.shiftServed/target*100)+'%';$('status').textContent='🧳 '+queue().length+' waiting  ·  🛏️ '+builtRooms()+' rooms  ·  💐 '+state.bouquets+'  ·  ⭐ '+state.rep;$('hint').textContent=zone?.label||('Shift '+(state.shift+1)+' · '+state.shiftServed+'/'+target+' guests · '+state.shiftLost+'/2 missed');$('action').textContent=zone?.action||'GO'}
function openPanel(type){panel=true;$('overlay').hidden=false;const b=$('sheetBody');b.dataset.type=type;if(type==='build'){b.innerHTML='<h2>🏗️ Grow the garden hotel</h2><p>Build new rooms along an expanding corridor. Each room earns more when decorated with farm bouquets.</p><div class="row"><span>🛏️</span><span class="detail"><b>New guest room</b><small>Room '+(builtRooms()+1)+' · walk to the glowing construction pad</small></span><button data-room="new" '+(state.money<roomPrice(builtRooms())?'disabled':'')+'>'+fmt(roomPrice(builtRooms()))+'</button></div>'+Object.entries(facilities).map(([id,f])=>'<div class="row"><span>'+f.icon+'</span><span class="detail"><b>'+f.name+'</b><small>'+({bath:'Restock supplies for guest comfort',lounge:'Display bouquets and earn extra tips',parking:'Welcome arriving drivers',cafe:'Sell garden jam and boost room revenue',pool:'Offer a premium resort stay'}[id])+'</small></span><button data-facility="'+id+'" '+(state.facilities[id]||state.money<f.cost?'disabled':'')+'>'+(state.facilities[id]?'OPEN':fmt(f.cost))+'</button></div>').join('')+'<h3>Room improvements</h3>'+state.rooms.map((r,i)=>'<div class="row"><span>🛏️</span><span class="detail">Room '+(i+1)+' · level '+r.level+'<small>'+(r.status==='dirty'?'Needs cleaning':r.flowers?'💐 Flowers displayed':'Add flowers in the room')+'</small></span><button data-improve="'+i+'" '+(state.money<95*r.level?'disabled':'')+'>'+fmt(95*r.level)+'</button></div>').join('')}
else if(type==='staff'){const roles=[['reception','🛎️','Check in waiting guests'],['cleaner','🧹','Clean rooms after checkout'],['gardener','🌻','Pick flowers'],['florist','🎀','Craft bouquets'],['attendant','🧻','Restock bathrooms']];b.innerHTML='<h2>👥 Your hotel team</h2><p>Helpers walk the resort and work automatically. Hire more to keep up with new rooms.</p>'+roles.map(([id,icon,detail])=>{const cost={reception:130,cleaner:160,gardener:135,florist:180,attendant:240}[id]*(1+state.staff[id]);return '<div class="row"><span>'+icon+'</span><span class="detail"><b>'+id[0].toUpperCase()+id.slice(1)+'</b><small>'+detail+' · '+state.staff[id]+' hired</small></span><button data-hire="'+id+'" '+(state.money<cost?'disabled':'')+'>'+fmt(cost)+'</button></div>'}).join('')}
else if(type==='story'){b.innerHTML='<h2>📖 Mira’s Garden Hotel</h2><div class="storyline">The old greenhouse stood beside an empty inn. Mira decided to reopen both: flowers greet each guest, and every visit helps the garden grow.</div><p>Chapter '+Math.min(state.story+1,quests.length)+' of '+quests.length+' · '+state.checked+' check-ins · '+state.served+' stays · '+state.cleaned+' rooms cleaned.</p><h3>Current goal</h3><p>'+(quests[state.story]?.text||'Create the resort you imagine.')+'</p><h3>Current challenge</h3><p>Shift '+(state.shift+1)+': check in '+(5+state.shift*2)+' guests before 2 leave. '+state.shiftServed+' served, '+state.shiftLost+' missed.</p><p>Watch for festival crowds, rain and VIP visits. Decorated rooms and facilities earn more.</p>'}
else if(type==='map'){b.innerHTML='<h2>🗺️ Explore the grounds</h2><p>Tap a destination to walk there instantly. You can also move freely with the joystick or tap the ground.</p><div class="map-grid">'+[['reception','🛎️ Reception'],['garden','🌻 Greenhouse'],['workshop','🎀 Bouquet workshop'],['jam','🫙 Jam kitchen'],['bath','🚿 Bathroom'],['lounge','💐 Flower lounge'],['parking','🚗 Parking'],['cafe','☕ Café'],['pool','🏊 Pool'],['newroom','🏗️ New wing']].map(([id,label])=>'<button data-travel="'+id+'">'+label+'</button>').join('')+'</div><p>Graphics: '+graphicMode+' · Rooms extend as you build.</p><a href="classic.html">Play the original flower workshop</a>'}
else if(type==='install')b.innerHTML='<h2>📲 Install Bloom & Boom</h2><p>On Android Chrome, open ⋮ → Add to Home screen → Install. Launch from the home screen for the full screen view. The game saves on this device and works offline after loading.</p>';
}
function closePanel(){panel=false;$('overlay').hidden=true;updateUI()}
$('close').onclick=closePanel;$('overlay').onclick=e=>{if(e.target===$('overlay'))closePanel();const btn=e.target.closest('button');if(!btn)return;if(btn.dataset.room==='new'){buyRoom();openPanel('build')}if(btn.dataset.facility)buyFacility(btn.dataset.facility);if(btn.dataset.improve!==undefined)improveRoom(+btn.dataset.improve);if(btn.dataset.hire)hire(btn.dataset.hire);if(btn.dataset.travel){const d=zones().find(v=>v.id===btn.dataset.travel);if(d){player.x=d.x;player.z=d.z+.8;waypoint=null;save();closePanel()}}};
$('action').onclick=interact;for(const id of ['map','build','story','staff'])$(id).onclick=()=>openPanel(id);
$('menu').onclick=()=>openPanel('map');$('install').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null}else openPanel('install')};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});
const stick=$('joystick');let pointer=null;function drag(e){const r=stick.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)/(r.width*.35),z=(e.clientY-r.top-r.height/2)/(r.height*.35),d=Math.max(1,Math.hypot(x,z));input.x=x/d;input.z=z/d;stick.firstElementChild.style.transform=`translate(${input.x*27}px,${input.z*27}px)`;waypoint=null}stick.onpointerdown=e=>{e.preventDefault();pointer=e.pointerId;stick.setPointerCapture(pointer);drag(e)};stick.onpointermove=e=>{if(e.pointerId===pointer)drag(e)};for(const name of ['pointerup','pointercancel'])stick.addEventListener(name,e=>{if(e.pointerId!==pointer)return;pointer=null;input.x=input.z=0;stick.firstElementChild.style.transform='translate(0,0)'});
window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d','e',' '].includes(e.key.toLowerCase())){e.preventDefault();keys.add(e.key.toLowerCase());if(e.key===' '||e.key.toLowerCase()==='e')interact()}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
const palette={grass:0x6caa73,grass2:0x80bc78,tile:0x9ed0d2,wall:0xc5dce0,wallTop:0xeaf9ef,wood:0xa95d4b,woodDark:0x7d4b40,cream:0xffe8b0,rose:0xf06f83,pink:0xf5a9bb,gold:0xffce64,leaf:0x459561,dark:0x2a6b5b,blue:0x619bc2,white:0xffffff,soil:0x9c663b,purple:0x966fbd,skin:0xf6be89,night:0x2b6883};
const mats={};for(const [k,v] of Object.entries(palette))mats[k]=new THREE.MeshStandardMaterial({color:v,roughness:.78});
function mesh(geo,mat,parent,x=0,y=0,z=0){const m=new THREE.Mesh(geo,typeof mat==='string'?mats[mat]:mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
function box(parent,x,y,z,w,h,d,mat){return mesh(new THREE.BoxGeometry(w,h,d),mat,parent,x,y,z)}
function ball(parent,x,y,z,r,mat){return mesh(new THREE.SphereGeometry(r,12,8),mat,parent,x,y,z)}
function cyl(parent,x,y,z,r,h,mat){return mesh(new THREE.CylinderGeometry(r,r,h,12),mat,parent,x,y,z)}
function oval(parent,x,y,z,rx,ry,rz,mat){const m=ball(parent,x,y,z,1,mat);m.scale.set(rx,ry,rz);return m}
function textSprite(str,{size=42,color='#24473c',back='#fff6df',width=240}={}){const c=document.createElement('canvas');c.width=width;c.height=74;const ctx=c.getContext('2d');ctx.fillStyle=back;ctx.beginPath();ctx.roundRect(4,3,width-8,62,18);ctx.fill();ctx.strokeStyle='#526e6c';ctx.lineWidth=4;ctx.stroke();ctx.fillStyle=color;ctx.font=`900 ${size}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(str,width/2,35);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const spr=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthTest:false}));spr.scale.set(width/90,.82,1);return spr}
function label(parent,text,x,y,z,scale=1){const sp=textSprite(text);sp.position.set(x,y,z);sp.scale.multiplyScalar(scale);parent.add(sp);return sp}
function flower3(parent,x,z,pink=false,s=1){const stem=cyl(parent,x,.26*s,z,.055*s,.5*s,'leaf');stem.rotation.z=.14;for(let j=0;j<7;j++){const a=j*Math.PI*2/7;oval(parent,x+Math.cos(a)*.21*s,.58*s,z+Math.sin(a)*.21*s,.18*s,.09*s,.12*s,pink?'pink':'gold')}ball(parent,x,.6*s,z,.13*s,'woodDark');oval(parent,x-.13*s,.25*s,z,.18*s,.04*s,.09*s,'leaf')}
function tree3(parent,x,z,n=1){cyl(parent,x,.55*n,z,.14*n,1.1*n,'woodDark');for(let j=0;j<3;j++){const h=1.3*n+j*.32*n,r=(.75-j*.12)*n;const m=mesh(new THREE.ConeGeometry(r,.92*n,7),'leaf',parent,x,h,z);m.rotation.y=j*.8}for(let j=0;j<5;j++){const a=j*1.8;ball(parent,x+Math.sin(a)*.49*n,1.7*n,z+Math.cos(a)*.4*n,.12*n,'pink')}}
function pad(parent,x,z,color,labelText){const material=new THREE.MeshStandardMaterial({color:palette[color]||0xffc766,transparent:true,opacity:.55,roughness:.8});const ring=mesh(new THREE.TorusGeometry(1.04,.065,6,24),material,parent,x,.055,z);ring.rotation.x=-Math.PI/2;ring.userData.pad=true;label(parent,labelText,x,1.4,z,.75)}
function person3(parent,look=0,staff=false){const group=new THREE.Group();parent.add(group);const clothes=['rose','blue','gold','purple','leaf'][look%5];oval(group,0,.07,0,.34,.06,.24,new THREE.MeshBasicMaterial({color:0x39775a,transparent:true,opacity:.35}));box(group,-.14,.23,0,.16,.43,.21,'woodDark');box(group,.14,.23,0,.16,.43,.21,'woodDark');cyl(group,0,.69,0,.33,.62,staff?'dark':clothes);ball(group,0,1.18,0,.31,'skin');oval(group,0,1.38,-.04,.33,.11,.31,staff?'gold':'woodDark');ball(group,-.11,1.22,.28,.032,'woodDark');ball(group,.11,1.22,.28,.032,'woodDark');box(group,-.42,.75,0,.15,.44,.16,'skin');box(group,.42,.75,0,.15,.44,.16,'skin');if(staff){cyl(group,0,1.51,0,.31,.15,'rose');box(group,0,.76,.28,.34,.15,.05,'cream')}return group}
function room3(parent,i){const p=roomPos(i),r=state.rooms[i],g=new THREE.Group();g.position.set(p.x,0,p.z);parent.add(g);const col=['cream','pink','blue','purple'][i%4];box(g,0,-.03,0,4.45,.14,5.2,i%2?'tile':'cream');box(g,0,.48,-2.56,4.55,.96,.25,'wall');box(g,p.x>0?2.25:-2.25,.48,0,.25,.96,5.15,'wall');box(g,0,.93,-2.56,4.6,.11,.3,'wallTop');box(g,p.x>0?2.25:-2.25,.93,0,.3,.11,5.15,'wallTop');box(g,0,.08,.3,3.15,.09,3.55,col);const bedx=p.x>0?1.13:-1.13;box(g,bedx,.33,-.8,1.65,.53,2.15,'woodDark');box(g,bedx,.63,-.85,1.55,.16,1.85,'white');box(g,bedx,.75,-1.22,1.5,.13,1.14,col);box(g,bedx,.79,-.05,1.2,.1,.32,'cream');box(g,-bedx,.29,-.7,.65,.54,.64,'wood');cyl(g,-bedx,.68,-.7,.23,.28,'gold');ball(g,-bedx,.93,-.7,.17,'cream');if(r.flowers){cyl(g,-bedx,.63,.7,.16,.47,'white');for(let a=0;a<4;a++)flower3(g,-bedx+(a-1.5)*.1,.72+a*.08,a%2,.6)}if(r.status==='dirty'){for(let k=0;k<3;k++)oval(g,(k-1)*.45,.11,1.32,.17,.035,.1,'woodDark')}label(g,'ROOM '+(i+1),0,1.12,2.2,.61);if(r.level>1)label(g,'★'.repeat(Math.min(4,r.level)),0,1.97,.1,.4);return g}
function build3DWorld(){if(!scene)return;if(world){scene.remove(world);world.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material?.map&&o.material.map.isTexture)o.material.map.dispose()})}world=new THREE.Group();scene.add(world);const far=8+Math.ceil((state.rooms.length+1)/2)*6.2;box(world,0,-.28,(far-5)/2,43,.45,far+40,'grass');for(let j=0;j<110;j++){const x=-20+(j*7.97)%40,z=-18+(j*13.73)%(far+34);if(Math.abs(x)<7&&z>0||Math.abs(x+10)<5&&z<-4)continue;box(world,x,-.04,z,.3+(j%3)*.18,.015,.18+(j%2)*.1,j%2?'grass2':'leaf')}
for(let j=0;j<26;j++){const x=(j%2?1:-1)*(15+j%3),z=-16+(j*4.67)%(far+23);tree3(world,x,z,.8+j%3*.13)}
// Hotel corridor grows with its rooms; no fixed end wall until the next expansion.
box(world,0,-.02,(far-8)/2,4.3,.14,far+9,'tile');for(let j=-9;j<far;j+=2.1){box(world,0,.055,j,4.05,.016,.045,'white');box(world,-1.7,.064,j,.07,.018,.65,'blue');box(world,1.7,.064,j,.07,.018,.65,'blue')}
for(let z=-9;z<far;z+=3.1){box(world,-2.16,.32,z,.15,.64,2.8,'wall');box(world,2.16,.32,z,.15,.64,2.8,'wall');box(world,-2.16,.66,z,.2,.075,2.8,'wallTop');box(world,2.16,.66,z,.2,.075,2.8,'wallTop')}
// Curved front desk, register and money stack.
box(world,0,.42,-5.0,3.5,.82,.72,'wood');box(world,0,.85,-5.0,3.65,.13,.82,'woodDark');box(world,-1,.94,-4.8,.52,.12,.3,'gold');box(world,1,.98,-4.85,.28,.18,.35,'cream');label(world,'GARDEN HOTEL',0,2.3,-5.2,.8);for(let j=0;j<Math.min(10,Math.floor(state.money/180));j++){box(world,1.3,1+j*.13,-4.7,.52,.11,.28,'leaf');box(world,1.3,1.11+j*.13,-4.7,.42,.012,.3,'gold')}
// Separate greenhouse and making stations connect directly to the resort.
box(world,-10,-.03,-8,7,.15,7,'soil');for(let row=0;row<4;row++){box(world,-12.2+row*1.45,.2,-8,1.04,.38,5.2,'wood');box(world,-12.2+row*1.45,.43,-8,.85,.12,5.05,'soil');for(let j=0;j<6;j++)flower3(world,-12.2+row*1.45,-10+j*.78,(j+row)%3===0,.78)}pad(world,-10,-8,'gold','PICK');box(world,-5,.43,-8,2.7,.78,1.7,'wood');box(world,-5,.86,-8,2.8,.12,1.8,'cream');for(let i=0;i<4;i++)flower3(world,-5.9+i*.53,-8.4,i%2,.6);label(world,'BOUQUETS',-5,1.72,-8,.6);pad(world,-5,-8,'pink','MAKE');box(world,-5,.46,-12,1.8,.9,1.5,'wood');cyl(world,-5,1.0,-12,.6,.28,'purple');label(world,'JAM',-5,1.85,-12,.6);pad(world,-5,-12,'purple','COOK');
for(let i=0;i<state.rooms.length;i++)room3(world,i);
if(state.rooms.length<20){const i=state.rooms.length,p=roomPos(i);box(world,p.x,-.04,p.z,4.3,.12,5.1,'soil');box(world,p.x,.01,p.z,4.0,.02,4.8,'grass2');pad(world,p.x>0?2.15:-2.15,p.z,'gold',fmt(roomPrice(i)));label(world,'ROOM '+(i+1),p.x,1,p.z,.65)}
// New amenities appear as complete spaces rather than a stationary menu tile.
for(const [id,f] of Object.entries(facilities)){const open=state.facilities[id];box(world,f.x,-.04,f.z,4.4,.15,4.4,open?'cream':'soil');if(open){if(id==='bath'){box(world,f.x,.35,f.z,2.2,.66,1.3,'white');box(world,f.x,.75,f.z,.9,.18,.8,'blue');for(let j=0;j<Math.min(5,state.bathStock);j++)cyl(world,f.x-1+j*.45,1,f.z-1.2,.13,.34,'white')}if(id==='lounge'){box(world,f.x,.35,f.z,2.7,.65,1.3,'wood');for(let j=0;j<6;j++)flower3(world,f.x-1.25+j*.5,f.z+(j%2)*.3,j%2,.8)}if(id==='parking'){box(world,f.x,.03,f.z,3.6,.08,2.6,'tile');box(world,f.x,.35,f.z,.95,.5,1.7,'rose');box(world,f.x,.67,f.z-.3,1.1,.16,.75,'white');for(const dx of [-.5,.5])cyl(world,f.x+dx,.15,f.z+.67,.18,.2,'woodDark')}if(id==='cafe'){box(world,f.x,.46,f.z,3.1,.9,1.25,'wood');box(world,f.x,.96,f.z,3.2,.12,1.36,'cream');for(let j=0;j<3;j++)cyl(world,f.x-1+j*.9,1.12,f.z,.27,.24,'pink')}if(id==='pool'){box(world,f.x,.1,f.z,3.7,.25,3.4,'white');box(world,f.x,.16,f.z,3.2,.08,2.9,'blue');for(let j=0;j<Math.min(4,state.poolStock);j++)ball(world,f.x-1.2+j*.7,.25,f.z+.3,.16,'white')}label(world,f.name.toUpperCase(),f.x,1.75,f.z-1.3,.57)}else label(world,f.icon+' '+fmt(f.cost),f.x,1.12,f.z,.62);pad(world,f.x,f.z,open?'leaf':'gold',open?'WORK':'BUILD')}
changedWorld=false}
function setup3D(){const c=$('view');try{renderer=new THREE.WebGLRenderer({canvas:c,antialias:false,powerPreference:'default'});c.addEventListener('webglcontextlost',event=>{event.preventDefault();fallback()},{once:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.38;scene=new THREE.Scene();scene.background=new THREE.Color(0xa6dfdb);scene.fog=new THREE.Fog(0xa6dfdb,45,85);camera=new THREE.OrthographicCamera(-10,10,10,-10,.1,130);const hemi=new THREE.HemisphereLight(0xdff8ff,0x8fa66f,2.1);scene.add(hemi);const sun=new THREE.DirectionalLight(0xffefd5,2.3);sun.position.set(-12,24,13);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-28;sun.shadow.camera.right=28;sun.shadow.camera.top=30;sun.shadow.camera.bottom=-30;sun.shadow.bias=-.0004;scene.add(sun);avatar=person3(scene,2,true);graphicMode='3D WebGL';build3DWorld();return true}catch(e){console.warn('3D unavailable, using illustrated game',e);fallback();return false}}
function staffLocation(id,j,t){const d=Math.sin(t*.0007+j),dirty=state.rooms.findIndex(r=>r.status==='dirty'),target=dirty>=0?roomPos(dirty):{x:0,z:2};const base={reception:[-.9,-4.2],cleaner:[target.x,target.z+.5],gardener:[-10,-7.4],florist:[-5,-7],attendant:[state.facilities.pool?-9:4.4,state.facilities.pool?15:-3.4]}[id];return{x:base[0]+Math.sin(t*.0015+j)*.4+j*.55,z:base[1]+d*.3}}
function render3D(t){if(changedWorld)build3DWorld();const w=$('view').clientWidth,h=$('view').clientHeight;if(!w||!h)return;renderer.setSize(w,h,false);const halfH=9.1,halfW=halfH*w/h;camera.left=-halfW;camera.right=halfW;camera.top=halfH;camera.bottom=-halfH;camera.updateProjectionMatrix();camera.position.lerp(new THREE.Vector3(player.x+1.8,16,player.z+11.8),.075);camera.lookAt(player.x,0,player.z+1.2);avatar.position.set(player.x,Math.sin(t*.008)*.055,player.z);avatar.rotation.y=player.heading;for(const g of state.guests){let a=actors.get(g.id);if(!a){a=person3(scene,g.look);actors.set(g.id,a)}a.position.set(g.x,Math.sin(t*.006+g.id)*.035,g.z);a.rotation.y=g.phase==='leave'?Math.PI:0}for(const [id,a] of actors)if(!state.guests.some(g=>g.id===id)){scene.remove(a);actors.delete(id)}for(const [id,n] of Object.entries(state.staff))for(let j=0;j<n;j++){const key=id+j;let a=staffActors.get(key);if(!a){a=person3(scene,(j+3)%5,true);staffActors.set(key,a)}const p=staffLocation(id,j,t);a.position.set(p.x,Math.sin(t*.008+j)*.04,p.z)}renderer.render(scene,camera)}
const art={};for(const name of ['grass','garden','hero','tree','workshop','kitchen','hotel-room','hotel-lobby','hotel-desk']){const im=new Image();im.src='./assets/'+name+'.webp';art[name]=im}
function draw2D(t){const c=canvas2d;if(!c)return;const el=$('view'),w=el.clientWidth,h=el.clientHeight,d=Math.min(devicePixelRatio||1,1.5);if(el.width!==Math.round(w*d)||el.height!==Math.round(h*d)){el.width=Math.round(w*d);el.height=Math.round(h*d)}c.setTransform(d,0,0,d,0,0);const s=clamp(w/9,30,52),P=(x,z,y=0)=>[w/2+(x-player.x)*s+(z-player.z)*s*.08,h*.57+(z-player.z)*s*.66-y*s];const rect=(x,z,ww,hh,col,height=0)=>{const p=P(x,z,height);c.fillStyle=col;c.fillRect(p[0]-ww*s/2,p[1]-hh*s*.66/2,ww*s,hh*s*.66)};const round=(x,y,ww,hh,r,col)=>{c.fillStyle=col;c.beginPath();c.roundRect(x,y,ww,hh,r);c.fill()};const sprite=(im,x,z,ww,hh)=>{if(!im?.complete||!im.naturalWidth)return;const p=P(x,z);c.drawImage(im,p[0]-ww*s/2,p[1]-hh*s,ww*s,hh*s)};const circle=(x,z,r,col)=>{const p=P(x,z);c.fillStyle=col;c.beginPath();c.ellipse(p[0],p[1],r*s,r*s*.42,0,0,7);c.fill()};const txt=(text,x,z,color='#3c5551',sz=11)=>{const p=P(x,z);c.font=`900 ${sz}px system-ui`;c.textAlign='center';c.lineWidth=3;c.strokeStyle='#fffdf0';c.strokeText(text,p[0],p[1]);c.fillStyle=color;c.fillText(text,p[0],p[1])};const bg=c.createLinearGradient(0,0,0,h);bg.addColorStop(0,'#b5e5dd');bg.addColorStop(.18,'#91c99c');bg.addColorStop(1,'#5f9d71');c.fillStyle=bg;c.fillRect(0,0,w,h);if(art.grass?.complete&&art.grass.naturalWidth){c.globalAlpha=.23;c.fillStyle=c.createPattern(art.grass,'repeat');c.fillRect(0,0,w,h);c.globalAlpha=1}
const far=8+Math.ceil((state.rooms.length+1)/2)*6.2;rect(0,(far-8)/2,4.2,far+9,'#9ed5d7');for(let z=-10;z<far;z+=2.1){rect(-1.55,z,.045,1.4,'#d9f8ee');rect(1.55,z,.045,1.4,'#d9f8ee')}
for(const [x,z] of [[-16,-4],[-15,3],[13,4],[13,12],[-14,15]])sprite(art.tree,x,z,2.3,2.4);
rect(-10,-8,7,7,'#94643e');sprite(art.garden,-10,-7,6,3.8);sprite(art.workshop,-5,-8,3.2,2.6);sprite(art.kitchen,-5,-12,3.2,2.6);sprite(art['hotel-lobby'],0,-5.8,5.3,4.1);
for(let i=0;i<state.rooms.length;i++){const p=roomPos(i),r=state.rooms[i],pt=P(p.x,p.z),ww=4.35*s,hh=5.1*s*.66;if(pt[1]<-hh-100||pt[1]>h+hh+100)continue;c.fillStyle='#315f5a33';c.fillRect(pt[0]-ww/2+4,pt[1]-hh/2+7,ww,hh);if(art['hotel-room']?.complete&&art['hotel-room'].naturalWidth)sprite(art['hotel-room'],p.x,p.z+1.3,5.5,4.2);else{round(pt[0]-ww/2,pt[1]-hh/2,ww,hh,9,i%2?'#a8d6d0':'#eee4c5');c.strokeStyle='#80a8ab';c.lineWidth=7;c.strokeRect(pt[0]-ww/2,pt[1]-hh/2,ww,hh);round(pt[0]-ww*.37,pt[1]-hh*.35,ww*.46,hh*.53,8,'#9b6c54');round(pt[0]-ww*.35,pt[1]-hh*.31,ww*.42,hh*.48,8,'#fffaf0');round(pt[0]-ww*.35,pt[1]-hh*.19,ww*.42,hh*.26,8,i%2?'#8fc3d3':'#efa5b5');round(pt[0]+ww*.15,pt[1]-hh*.1,ww*.18,hh*.2,5,'#b58158')}if(r.flowers){txt('💐',p.x+.95,p.z+.35,'#fff',22)}if(r.status==='dirty'){txt('🧹',p.x,p.z+.8,'#be574c',20)}else if(r.status==='occupied'){txt('💤',p.x,p.z+.8,'#537b91',16)}txt('ROOM '+(i+1),p.x,p.z+2.3,'#3f7076',10)}
if(state.rooms.length<20){const p=roomPos(state.rooms.length);rect(p.x,p.z,4.4,5.2,'#91b98a');txt('🏗️ '+fmt(roomPrice(state.rooms.length)),p.x,p.z,'#765439',12)}
for(const [id,f] of Object.entries(facilities)){const open=state.facilities[id];rect(f.x,f.z,4.1,3.5,open?'#ffe9c1':'#aac98b');txt(f.icon+' '+(open?f.name:fmt(f.cost)),f.x,f.z,'#4d6262',12)}
if(art['hotel-desk']?.complete&&art['hotel-desk'].naturalWidth)sprite(art['hotel-desk'],0,-4.5,3.8,2.4);else{rect(0,-5,3.5,.85,'#bd6f58');rect(0,-4.6,3.3,.26,'#ffdfa3');txt('🛎️',0,-5,'#fff',21)}for(let i=0;i<Math.min(8,Math.floor(state.money/200));i++)rect(1.2,-5.2-i*.15,.6,.12,'#3dc871');
for(const z of zones()){if(Math.abs(z.x-player.x)>8||Math.abs(z.z-player.z)>12)continue;circle(z.x,z.z,.8,'#fff9d06b');const p=P(z.x,z.z);c.strokeStyle=z.id==='newroom'?'#f6c76b':'#fefdec';c.lineWidth=2;c.beginPath();c.ellipse(p[0],p[1],s*.8,s*.32,0,0,7);c.stroke()}
function actor(x,z,look,playerActor=false){const p=P(x,z),u=playerActor?1.05:.78;circle(x,z,.35*u,'#31593855');if(art.hero?.complete&&art.hero.naturalWidth){c.save();if(look)c.filter=`hue-rotate(${look*43}deg)`;c.drawImage(art.hero,p[0]-s*.55*u,p[1]-s*1.68*u,s*1.1*u,s*1.68*u);c.restore()}else{round(p[0]-s*.22*u,p[1]-s*.95*u,s*.44*u,s*.62*u,7,look%2?'#f7a974':'#e8758f');c.fillStyle='#f6c38e';c.beginPath();c.arc(p[0],p[1]-s*1.1*u,s*.22*u,0,7);c.fill()}}
for(const g of state.guests){actor(g.x,g.z,g.look);if(g.phase==='queue'){const p=P(g.x,g.z,1.55);round(p[0]-15,p[1]-5,30,5,4,'#e4e4c5');round(p[0]-15,p[1]-5,30*clamp(g.patience/g.max,0,1),5,4,g.patience<15?'#ed6156':'#77bb70');if(g.vip)txt('★',g.x,g.z-.2,'#e6af43',13)}}for(const [id,n] of Object.entries(state.staff))for(let j=0;j<n;j++){const p=staffLocation(id,j,t);actor(p.x,p.z,j+2)}actor(player.x,player.z,0,true);
for(const e of effects){const p=P(e.x,e.z,e.y);c.globalAlpha=1-e.age/1.1;round(p[0]-39,p[1]-12,78,22,10,'#fff9dc');c.fillStyle='#43744f';c.textAlign='center';c.font='900 12px system-ui';c.fillText(e.label,p[0],p[1]+3);c.globalAlpha=1}}
function fallback(){renderer?.dispose();renderer=null;scene=null;const old=$('view'),next=document.createElement('canvas');next.id='view';next.setAttribute('aria-label','Illustrated Garden Hotel game');old.replaceWith(next);canvas2d=next.getContext('2d');graphicMode='Illustrated (3D unavailable)';if(window.bloomGameReady)bindWorldTap()}
function bindWorldTap(){$('view').addEventListener('pointerdown',e=>{if(panel)return;const c=$('view'),r=c.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*2-1,y=-(e.clientY-r.top)/r.height*2+1;if(renderer&&camera){const ray=new THREE.Raycaster();ray.setFromCamera({x,y},camera);const hit=new THREE.Vector3();if(ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),0),hit))waypoint={x:hit.x,z:hit.z}}else{const s=clamp(r.width/9,30,52);waypoint={x:player.x+(e.clientX-r.left-r.width/2)/s,z:player.z+(e.clientY-r.top-r.height*.57)/(s*.66)}}})}
function blocked(x,z){if(Math.abs(x)>20||z<-17||z>8+Math.ceil((state.rooms.length+1)/2)*6.2+1)return true;if(Math.abs(x)<1.85&&z>-5.45&&z<-4.55)return true;for(let i=0;i<state.rooms.length;i++){const p=roomPos(i),bedx=p.x>0?p.x+1.12:p.x-1.12;if(Math.abs(x-bedx)<1.05&&Math.abs(z-(p.z-.8))<1.35)return true}return false}
function frame(t){const dt=Math.min(.05,(t-last)/1000||0);last=t;if(!panel){let ix=input.x+(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),iz=input.z+(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);if(Math.abs(ix)+Math.abs(iz)<.06&&waypoint){const dx=waypoint.x-player.x,dz=waypoint.z-player.z,d=Math.hypot(dx,dz);if(d<.24)waypoint=null;else{ix=dx/d;iz=dz/d}}const n=Math.max(1,Math.hypot(ix,iz));ix/=n;iz/=n;player.vx+=(ix*5-player.vx)*Math.min(1,dt*11);player.vz+=(iz*5-player.vz)*Math.min(1,dt*11);const nx=player.x+player.vx*dt,nz=player.z+player.vz*dt;if(!blocked(nx,player.z))player.x=nx;else player.vx=0;if(!blocked(player.x,nz))player.z=nz;else player.vz=0;if(Math.hypot(player.vx,player.vz)>.3)player.heading=Math.atan2(player.vx,player.vz);const newZone=nearest();if(newZone?.id!==zone?.id||newZone?.i!==zone?.i){zone=newZone;workTime=0;updateUI()}if(zone){workTime+=dt;if(workTime>.8){workTime=0;if(zone.id==='reception'&&queue().length)checkIn();else if(zone.id==='garden')pick();else if(zone.id==='workshop'&&state.flowers>=2)craft();else if(zone.id==='room'&&state.rooms[zone.i]?.status==='dirty')cleanRoom(zone.i)}}guestTick(dt);staffTick(dt);eventTick(dt);uiTime+=dt;if(uiTime>.25){uiTime=0;updateUI();if(Math.floor(t)%4200<30)save()}}for(const e of effects){e.age+=dt;e.y+=dt*1.3}for(let i=effects.length-1;i>=0;i--)if(effects[i].age>1.1)effects.splice(i,1);try{renderer?render3D(t):draw2D(t)}catch(e){console.warn('Graphics failed, switching to illustrated mode',e);fallback()}requestAnimationFrame(frame)}
setup3D();bindWorldTap();progress();updateUI();$('loading').hidden=true;window.bloomHotel={state,zones,roomPrice,checkIn,cleanRoom,buyRoom,interact,renderMode:()=>graphicMode};window.bloomGameReady=true;requestAnimationFrame(frame);
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
