/* Sunny Acres 3D — standalone WebGL renderer; no external runtime dependencies. */
(() => {
const canvas=document.getElementById('farm3d');
const gl=canvas.getContext('webgl',{antialias:true,alpha:false});
if(!gl){canvas.style.display='none';return}
const V=`attribute vec3 p;attribute vec3 col;attribute vec3 normal;uniform mat4 vp;varying vec3 vcolor;void main(){float light=.57+max(dot(normalize(normal),normalize(vec3(-.4,1.,.6))),0.)*.43;vcolor=col*light;gl_Position=vp*vec4(p,1.);}`;
const F=`precision mediump float;varying vec3 vcolor;void main(){gl_FragColor=vec4(vcolor,1.);}`;
function shader(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}
const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,V));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,F));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);
const attrs=['p','col','normal'].map(a=>gl.getAttribLocation(program,a)),uniform=gl.getUniformLocation(program,'vp'),buffer=gl.createBuffer();gl.enable(gl.DEPTH_TEST);gl.clearColor(.66,.85,.92,1);
const colors={grass:'#80b852',grass2:'#73a948',soil:'#a66a41',soil2:'#8b5438',wood:'#9d6741',cream:'#f7e6a8',yellow:'#ffd445',orange:'#e89530',brown:'#794c31',red:'#e55746',green:'#4c9a42',dark:'#315b36',blue:'#51b9dc',white:'#f8f4e6',skin:'#e7ad7e',roof:'#d45542',shadow:'#669c48'};
const rgb=h=>{h=colors[h]||h;return [parseInt(h.slice(1,3),16)/255,parseInt(h.slice(3,5),16)/255,parseInt(h.slice(5,7),16)/255]};let vertices=[];
function tri(a,b,c,color){const co=rgb(color),u=b.map((x,i)=>x-a[i]),v=c.map((x,i)=>x-a[i]),n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]],l=Math.hypot(...n)||1;for(const p of [a,b,c])vertices.push(...p,...co,n[0]/l,n[1]/l,n[2]/l)}
function quad(a,b,c,d,color){tri(a,b,c,color);tri(a,c,d,color)}
function box(x,y,z,w,h,d,color){const x0=x-w/2,x1=x+w/2,y0=y,y1=y+h,z0=z-d/2,z1=z+d/2;quad([x0,y1,z1],[x1,y1,z1],[x1,y1,z0],[x0,y1,z0],color);quad([x0,y0,z1],[x0,y1,z1],[x0,y1,z0],[x0,y0,z0],color);quad([x1,y0,z0],[x1,y1,z0],[x1,y1,z1],[x1,y0,z1],color);quad([x0,y0,z1],[x1,y0,z1],[x1,y1,z1],[x0,y1,z1],color);quad([x1,y0,z0],[x0,y0,z0],[x0,y1,z0],[x1,y1,z0],color)}
function prism(x,y,z,r,h,color,sides=8){for(let j=0;j<sides;j++){const a=j*2*Math.PI/sides,b=(j+1)*2*Math.PI/sides;const p=[x+Math.cos(a)*r,y,z+Math.sin(a)*r],q=[x+Math.cos(b)*r,y,z+Math.sin(b)*r],u=[p[0],y+h,p[2]],v=[q[0],y+h,q[2]];quad(p,q,v,u,color);tri([x,y+h,z],u,v,color)}}
function cone(x,y,z,r,h,color,sides=8){for(let j=0;j<sides;j++){const a=j*2*Math.PI/sides,b=(j+1)*2*Math.PI/sides;tri([x+Math.cos(a)*r,y,z+Math.sin(a)*r],[x+Math.cos(b)*r,y,z+Math.sin(b)*r],[x,y+h,z],color)}}
function ellipsoid(x,y,z,rx,ry,rz,color){const rings=5,sides=9;for(let i=0;i<rings;i++){const a=Math.PI*i/rings,b=Math.PI*(i+1)/rings;for(let j=0;j<sides;j++){const c=2*Math.PI*j/sides,d=2*Math.PI*(j+1)/sides;const pt=(t,u)=>[x+Math.sin(t)*Math.cos(u)*rx,y+Math.cos(t)*ry,z+Math.sin(t)*Math.sin(u)*rz];quad(pt(a,c),pt(a,d),pt(b,d),pt(b,c),color)}}}
function petal(x,y,z,a,scale,color){const dx=Math.cos(a),dz=Math.sin(a),tx=-dz,tz=dx;const r=.095*scale,r2=.37*scale,w=.14*scale;tri([x+dx*r,y,z+dz*r],[x+dx*r2+tx*w,y+.045,z+dz*r2+tz*w],[x+dx*r2+tx*w*.3,y+.06,z+dz*r2+tz*w*.3],color);tri([x+dx*r,y,z+dz*r],[x+dx*r2+tx*w*.3,y+.06,z+dz*r2+tz*w*.3],[x+dx*r2-tx*w,y+.045,z+dz*r2-tz*w],color)}
function sunflower(x,z,s=1){prism(x,0,z,.055*s,.48*s,'green',6);ellipsoid(x-.13*s,.25*s,z,.2*s,.065*s,.11*s,'green');ellipsoid(x+.13*s,.34*s,z,.2*s,.055*s,.11*s,'green');for(let i=0;i<9;i++)petal(x,.68*s,z,i*2*Math.PI/9,s,'yellow');ellipsoid(x,.7*s,z,.15*s,.1*s,.15*s,'brown')}
function carrot(x,z){prism(x,0,z,.08,.3,'green',6);for(let i=0;i<3;i++)cone(x+Math.cos(i*2.1)*.08,.23,z+Math.sin(i*2.1)*.08,.075,.24,'green',5);cone(x,.04,z,.17,.23,'orange',7)}
function strawberry(x,z){prism(x,0,z,.06,.32,'green',6);for(let i=0;i<3;i++){const a=i*2.1;ellipsoid(x+Math.cos(a)*.15,.34,z+Math.sin(a)*.15,.115,.14,.105,'red')}cone(x,.39,z,.18,.15,'green',6)}
function farmhand(t){let x=-3.5+Math.sin(t*.00065)*.19,z=2.22;ellipsoid(x,.15,z,.25,.12,.2,'shadow');prism(x,.15,z,.18,.38,'blue');ellipsoid(x,.68,z,.22,.23,.21,'skin');prism(x,.83,z,.35,.065,'yellow');cone(x,.88,z,.24,.2,'brown');box(x-.13,.08,z,.12,.22,.15,'brown');box(x+.13,.08,z,.12,.22,.15,'brown');box(x-.3,.39,z,.13,.3,.12,'skin');box(x+.3,.39,z,.13,.3,.12,'skin')}
function barn(){box(3.1,0,2.45,1.5,1.32,1.24,'cream');cone(3.1,1.18,2.45,1.16,.73,'roof',4);box(3.1,.02,3.08,.53,.8,.04,'wood');box(3.1,.58,3.11,.22,.22,.04,'blue')}
function scenery(t){box(0,-.27,0,11,.27,8,'grass');box(0,-.32,0,12,.07,9,'grass2');for(let i=0;i<7;i++){const x=-5+i*1.65;box(x,0,-3.61,.13,.48,.13,'wood');box(x,.24,-3.61,1.65,.11,.1,'cream')}for(let i=0;i<5;i++){const z=-2.7+i*1.48;box(-5.03,0,z,.13,.48,.13,'wood');box(-5.03,.23,z,.1,.1,1.5,'cream')}for(const [x,z] of [[-4.45,-2.75],[4.35,-2.6],[4.65,.4]]){prism(x,0,z,.13,.76,'wood');cone(x,.55,z,.66,1.35,'dark');cone(x,1.04,z,.49,.95,'green')}barn();farmhand(t)}
function plot(i,st,t){const col=i%3,row=Math.floor(i/3),x=(col-1)*2.45,z=(row-.5)*2.25-.5;const unlocked=i<st.plots;box(x,.012,z,2.16,.16,1.94,unlocked?'wood':'grass2');box(x,.176,z,2.01,.045,1.79,unlocked?'soil':'grass');if(!unlocked){box(x,.22,z,.46,.23,.46,'cream');cone(x,.45,z,.22,.22,'yellow');return}const f=st.fields[i];if(!f){for(let j=0;j<3;j++)box(x,.225,z+(j-1)*.48,1.75,.025,.14,'soil2');return}const ready=Date.now()>=f.ready;const bob=Math.sin(t*.002+i)*.025;for(let j=0;j<9;j++){const px=x+((j%3)-1)*.54,pz=z+(Math.floor(j/3)-1)*.47;if(ready){if(f.crop==='sunflower')sunflower(px,.0+pz,0.76+bob);else if(f.crop==='carrot')carrot(px,pz);else strawberry(px,pz)}else{prism(px,.22,pz,.055,.13,'green',5);ellipsoid(px-.07,.37,pz,.11,.03,.06,'green');ellipsoid(px+.07,.36,pz,.11,.03,.06,'green')}}}
function normalize(a){const l=Math.hypot(...a)||1;return a.map(v=>v/l)}
function cross(a,b){return [a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]}
function lookAt(eye,at){const z=normalize(eye.map((v,i)=>v-at[i])),x=normalize(cross([0,1,0],z)),y=cross(z,x);return [x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-x.reduce((a,v,i)=>a+v*eye[i],0),-y.reduce((a,v,i)=>a+v*eye[i],0),-z.reduce((a,v,i)=>a+v*eye[i],0),1]}
function perspective(fov,aspect,near,far){const f=1/Math.tan(fov/2);return [f/aspect,0,0,0,0,f,0,0,0,0,(far+near)/(near-far),-1,0,0,2*far*near/(near-far),0]}
function mul(a,b){let o=new Array(16).fill(0);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o}
let state=null,angle=-.45,zoom=14.3,handler=()=>{},down=null,vp;
function draw(t){const w=canvas.clientWidth,h=canvas.clientHeight,dpr=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);gl.viewport(0,0,canvas.width,canvas.height)}if(!w||!h){requestAnimationFrame(draw);return}vertices=[];scenery(t);if(state)for(let i=0;i<6;i++)plot(i,state,t);const aspect=w/h;const distance=zoom*(aspect<1?.93:1);const eye=[Math.sin(angle)*distance*.75,distance*.79,Math.cos(angle)*distance*.75];vp=mul(perspective(Math.PI/3,aspect,.1,100),lookAt(eye,[0,.1,0]));gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(program);gl.uniformMatrix4fv(uniform,false,new Float32Array(vp));gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(vertices),gl.DYNAMIC_DRAW);for(let i=0;i<3;i++){gl.enableVertexAttribArray(attrs[i]);gl.vertexAttribPointer(attrs[i],3,gl.FLOAT,false,36,i*12)}gl.drawArrays(gl.TRIANGLES,0,vertices.length/9);if(vertices.length){document.getElementById('fallbackFarm').classList.add('rendered')}requestAnimationFrame(draw)}
function project(x,y,z){const v=[x,y,z,1],o=[0,0,0,0];for(let r=0;r<4;r++)for(let c=0;c<4;c++)o[r]+=vp[c*4+r]*v[c];return [(o[0]/o[3]+1)*canvas.clientWidth/2,(1-o[1]/o[3])*canvas.clientHeight/2]}
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);down={x:e.clientX,y:e.clientY,a:angle,moved:false}});
canvas.addEventListener('pointermove',e=>{if(!down)return;const dx=e.clientX-down.x;if(Math.abs(dx)>8||Math.abs(e.clientY-down.y)>8)down.moved=true;if(down.moved)angle=down.a-dx*.007});
canvas.addEventListener('pointerup',e=>{if(!down)return;if(!down.moved&&state){const rect=canvas.getBoundingClientRect(),p=[e.clientX-rect.left,e.clientY-rect.top];let best=-1,dist=Infinity;for(let i=0;i<6;i++){const x=((i%3)-1)*2.45,z=(Math.floor(i/3)-.5)*2.25-.5;const a=project(x,.24,z),d=Math.hypot((p[0]-a[0])*1.15,(p[1]-a[1])*1.55);if(d<dist){dist=d;best=i}}if(dist<Math.max(45,canvas.clientWidth*.115))handler(best)}down=null});
canvas.addEventListener('pointercancel',()=>down=null);
canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(10,Math.min(20,zoom+Math.sign(e.deltaY)*.7))},{passive:false});
window.farm3d={refresh(s){state=s},setPlotHandler(fn){handler=fn}};requestAnimationFrame(draw);
})();
